cv/urls.py
'''
Created on Jul 29, 2014

@author: mdesbois
'''
from django.conf.urls import patterns, url
from cv import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='cv_index'),
)

diana_website/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'diana_website.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^portfolio/', include("portfolio.urls")),
    url(r'^cv/', include("cv.urls")),
    url(r'^contact/$', 'main_app.views.contact', name ='main_app_contact' ),
    url(r'^$', 'main_app.views.home', name='main_app_home'),
    url(r'^(?P<catSlug>([a-z]+\-*[a-z]+\-*)+)$', 'main_app.views.index', name='main_app_index'),
    
    
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv/models.py
from django.db import models
from autoslug import AutoSlugField
import main_app
from django.core.urlresolvers import reverse
# Create your models here.

class SubCVCategory(main_app.models.CategoryAbstract):
    
    description = models.TextField(blank = True)
    category = models.ForeignKey('main_app.Category')
    display_title = models.CharField(max_length = 50, help_text = "Title that you will see in the menu")
    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return "#" + self.slug
    
    
    class Meta:
        app_label= "cv"
        ordering = ['position']
        
    
class CVItem(main_app.models.ContentAbstract):
    
    category = models.ForeignKey('SubCVCategory')
    position = models.IntegerField(help_text = "Position in the menu")
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        app_label= "cv"
        ordering = ['position']

portfolio/models.py
from django.db import models
import os
from autoslug import AutoSlugField
import main_app
from django.core.urlresolvers import reverse

# Create your models here.

        
        
class Project(main_app.models.ContentAbstract):
    
    cat = models.ForeignKey(main_app.models.Category)
    display_title = models.CharField(max_length = 50, help_text = "Title that you will see in the menu")
    
    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('portfolio_detailsProject', kwargs={'catSlug' :self.cat.slug, 'projectSlug': self.slug})
    
    class Meta:
        app_label= "portfolio"
        
    
 
 
class ImagesForGallery(models.Model):
    title = models.CharField(max_length = 20)
    description = models.CharField(max_length = 100, blank = True)
    
    onTop = models.BooleanField(default=False)
    project = models.ForeignKey(Project)
    
    mini = models.ImageField(upload_to="mini") 
    medium = models.ImageField(upload_to="medium")
    full = models.ImageField(upload_to="full") 
    
    def __unicode__(self):
        return self.title
   
    class Meta:
        app_label= "portfolio"

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Diana Bogdan</title>
<link rel="stylesheet" href="{% static "www/css/style.css" %}" media="screen, projection" />
<!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
{% block additionalCss %} {% endblock %}

{% block script %}
	 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="{% static "www/js/menu.js" %}" type="text/javascript" charset="utf-8"></script>
	{% endblock %}
</head>
<body>
	<div id="blockpage">
		<header>
			<a href="/"><div id="title">
					<h1>Diana Bogdan</h1>
					<h2>Architect</h2>
				</div></a>


		</header>
		<nav>
			<ul class="nav-main">
				{% for c in cats %}
					{% if c.project_set.all%}
					<li><a class="toggle-sub" href="{{ c.get_absolute_url }}">{{ c.title }}<img
						src="{% static "www/images/down.gif" %}" alt="down_arrow"/></a>
						<ul class="sub-menu">
						{% for p in c.project_set.all %}
								<li><a href="{{ p.get_absolute_url }}">{{ p.display_title }}</a></li>
							
						{% endfor %}
						</ul></li>
					{% comment %}
					{% elif c.subcvcategory_set.all %}
						<li><a class="toggle-sub" href="{{ c.get_absolute_url }}">{{ c.title }}<img
						src="{% static "www/images/down.gif" %}" alt="down_arrow"/></a>
						<ul class="sub-menu">
						{% for sub in c.subcvcategory_set.all %}
								<li><a href="{{ sub.get_absolute_url }}">{{ sub.display_title }}</a></li>
							
						{% endfor %}
						</ul></li>
					{% endcomment %}
					{% else %}
						<li><a href="{{ c.get_absolute_url }}">{{ c.title }}</a></li>
					{% endif %}
					
				{% endfor %}
				
			</ul>
				<a  id="dlpdf" href="{{ MEDIA_URL}}dianabogdan.pdf" title="Download my CV"><img src="{% static "www/images/pdf.png" %}" alt="pdf" /></a>
 		</nav>
		<section>
			{% block content %}
			<h1>{{item.title}}</h1>
			<article>
				{{ item.description|safe}}
			</article>
			{% endblock %}
		</section>

		<footer>
		<div class="separator"><!-- only to add border on top --></div>
			<div class="contactme">
				<h1>Diana BOGDAN</h1>
				<h2>Architect</h2>
				<h3>Contact Me:</h3>
				<a href="{{ contactCat.get_absolute_url }}"><img src="{% static "www/images/mail.png" %}" alt="mail" /></a> <a
								href="#"><img src="{% static "www/images/linkedin.png" %}" alt="linkedin"/></a>
			</div>

			<div class="about">
				<h1>About</h1>
				<blockquote>&ldquo;I'm Diana BOGDAN, a dynamic
					architect. I'm looking for opportunities which can be a new
					challenge.&rdquo;</blockquote>
			</div>
		</footer>
	
	</div>

	
</body>
</html>