cv/urls.py
'''
Created on Jul 29, 2014

@author: mdesbois
'''
from django.conf.urls import patterns, url
from cv import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='cv_index'),
)

diana_website/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'diana_website.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^portfolio/', include("portfolio.urls")),
    url(r'^cv/', include("cv.urls")),
    url(r'^contact/$', 'main_app.views.contact', name ='main_app_contact' ),
    url(r'^$', 'main_app.views.home', name='main_app_home'),
    url(r'^(?P<catSlug>([a-z]+\-*[a-z]+\-*)+)$', 'main_app.views.index', name='main_app_index'),
    
    
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv/models.py
from django.db import models
from autoslug import AutoSlugField
import main_app
from django.core.urlresolvers import reverse
# Create your models here.

class SubCVCategory(main_app.models.CategoryAbstract):
    
    description = models.TextField(blank = True)
    category = models.ForeignKey('main_app.Category')
    display_title = models.CharField(max_length = 50, help_text = "Title that you will see in the menu")
    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return "#" + self.slug
    
    
    class Meta:
        app_label= "cv"
        ordering = ['position']
        
    
class CVItem(main_app.models.ContentAbstract):
    
    category = models.ForeignKey('SubCVCategory')
    position = models.IntegerField(help_text = "Position in the menu")
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        app_label= "cv"
        ordering = ['position']

cv/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import *
from django.http import HttpResponse
from models import *
from django.core.urlresolvers import reverse


def index(request):
    
    sub = SubCVCategory.objects.all()
    
    return render(request,'cv.html',{'sub': sub})

cv/templates/cv.html
{% extends "base.html" %}

{% load staticfiles %}
{% block additionalCss %}
<link rel="stylesheet" href="{% static "cv/css/cv.css" %}" media="screen, projection" />
{% endblock %}



{% block content %}

{% for s in sub %}
	<article>
	<h1>{{s.title}}</h1>
	{{s.description|safe}}
	
	{% for i in s.cvitem_set.all %}
		<div class="slider-main">
			<div class="slider-content">
				<h3 class= "toggle">{{i.title}}</h3>
				<div class="slider-content-hidden">
				
					{{i.description|safe}}
				</div>
			</div>
		
		
		</div>
	
	
	{% endfor %}
	</article>
{% endfor %}

{% endblock %}

{% block script %} {{ block.super }} 
<script src="{% static "cv/js/slider.js" %}" type="text/javascript" charset="utf-8"></script>

{% endblock %}